<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dtaq" nsURI="http://www.asup.org/os/type/dtaq" nsPrefix="os-type-dtaq">
  <eClassifiers xsi:type="ecore:EClass" name="DataQueue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataQueueType" lowerBound="1"
        eType="#//DataQueueType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="keyLength" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxEntryLength" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="senderInfo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="#//DataQueueContent"
        containment="true"/>
    <eGenericSuperTypes eClassifier="ecore:EClass ../../org.asup.os.type/model/os-type.ecore#//TypedObject"/>
    <eGenericSuperTypes eClassifier="ecore:EClass ../../org.asup.os.core/model/os-core.ecore#//Container">
      <eTypeArguments eClassifier="#//DataQueueEntry"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataQueueContent">
    <eGenericSuperTypes eClassifier="ecore:EClass ../../org.asup.os.core/model/os-core.ecore#//ObjectContent">
      <eTypeArguments eClassifier="#//DataQueueEntry"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataQueueEntry" eSuperTypes="../../org.asup.os.omac/model/os-omac.ecore#//Object">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataQueueManager" abstract="true">
    <eOperations name="createDataQueue" lowerBound="1" eType="#//DataQueue" eExceptions="ecore:EDataType ../../org.asup.os.core/model/os-core.ecore#//OperatingSystemException">
      <eParameters name="ContextID" lowerBound="1" eType="ecore:EClass ../../org.asup.fw.core/model/fw-core.ecore#//ContextID"/>
      <eParameters name="library" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="type" lowerBound="1" eType="#//DataQueueType"/>
      <eParameters name="maxEntryLength" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eOperations name="writeDataQueue" lowerBound="1" eExceptions="ecore:EDataType ../../org.asup.os.core/model/os-core.ecore#//OperatingSystemException">
      <eParameters name="ContextID" lowerBound="1" eType="ecore:EClass ../../org.asup.fw.core/model/fw-core.ecore#//ContextID"/>
      <eParameters name="library" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="readDataQueue" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        eExceptions="ecore:EDataType ../../org.asup.os.core/model/os-core.ecore#//OperatingSystemException">
      <eParameters name="ContextID" lowerBound="1" eType="ecore:EClass ../../org.asup.fw.core/model/fw-core.ecore#//ContextID"/>
      <eParameters name="library" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="timeout" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      <eParameters name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="searchType" eType="#//DataQueueSearchType"/>
    </eOperations>
    <eOperations name="clearDataQueue" lowerBound="1" eExceptions="ecore:EDataType ../../org.asup.os.core/model/os-core.ecore#//OperatingSystemException">
      <eParameters name="ContextID" lowerBound="1" eType="ecore:EClass ../../org.asup.fw.core/model/fw-core.ecore#//ContextID"/>
      <eParameters name="library" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="peekDataQueue" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        eExceptions="ecore:EDataType ../../org.asup.os.core/model/os-core.ecore#//OperatingSystemException">
      <eParameters name="ContextID" lowerBound="1" eType="ecore:EClass ../../org.asup.fw.core/model/fw-core.ecore#//ContextID"/>
      <eParameters name="library" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="timeout" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      <eParameters name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="searchType" eType="#//DataQueueSearchType"/>
    </eOperations>
    <eOperations name="deleteDataQueue" eExceptions="ecore:EDataType ../../org.asup.os.core/model/os-core.ecore#//OperatingSystemException">
      <eParameters name="ContextID" lowerBound="1" eType="ecore:EClass ../../org.asup.fw.core/model/fw-core.ecore#//ContextID"/>
      <eParameters name="library" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eGenericSuperTypes eClassifier="ecore:EClass ../../org.asup.os.type/model/os-type.ecore#//TypedManager">
      <eTypeArguments eClassifier="#//DataQueue"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="ecore:EClass ../../org.asup.os.core/model/os-core.ecore#//ContentLockable">
      <eTypeArguments eClassifier="#//DataQueue"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DataQueueType">
    <eLiterals name="Fifo" value="10" literal="F"/>
    <eLiterals name="Lifo" value="20" literal="L"/>
    <eLiterals name="Keyed" value="30" literal="K"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DataQueueSearchType">
    <eLiterals name="Equal" value="10" literal="*EQ"/>
    <eLiterals name="NotEqual" value="20" literal="*NE"/>
    <eLiterals name="LessThan" value="30" literal="*LT"/>
    <eLiterals name="GreaterThan" value="40" literal="*GT"/>
    <eLiterals name="LessThanOrEqual" value="50" literal="*LE"/>
    <eLiterals name="GreaterThanOrEqual" value="60" literal="*GE"/>
  </eClassifiers>
</ecore:EPackage>
