<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="usrspc" nsURI="http://www.asup.org/os/type/usrspc" nsPrefix="os-type-usrspc">
  <eClassifiers xsi:type="ecore:EClass" name="UserSpace" eSuperTypes="../../org.asup.os.type/model/os-type.ecore#//TypedObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="header" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UserSpaceManager" abstract="true">
    <eGenericSuperTypes eClassifier="ecore:EClass ../../org.asup.os.type/model/os-type.ecore#//TypedManager">
      <eTypeArguments eClassifier="#//UserSpace"/>
    </eGenericSuperTypes>
  </eClassifiers>
</ecore:EPackage>
