<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="util" nsURI="http://www.asup.org/fw/util" nsPrefix="fw-util">
  <eClassifiers xsi:type="ecore:EClass" name="FileUtil" abstract="true" interface="true"
      eSuperTypes="../../org.asup.fw.core/model/fw-core.ecore#//Service">
    <eOperations name="getBaseName" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eParameters name="fileName" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IOUtil" abstract="true" interface="true"
      eSuperTypes="../../org.asup.fw.core/model/fw-core.ecore#//Service">
    <eOperations name="copy">
      <eParameters name="input" lowerBound="1" eType="ecore:EDataType ../../org.asup.fw.java/model/fw-java.ecore#//JavaInputStream"/>
      <eParameters name="output" lowerBound="1" eType="ecore:EDataType ../../org.asup.fw.java/model/fw-java.ecore#//JavaOutputStream"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ListUtil" abstract="true" interface="true"
      eSuperTypes="../../org.asup.fw.core/model/fw-core.ecore#//Service">
    <eOperations name="addFirst">
      <eTypeParameters name="E"/>
      <eParameters name="list" lowerBound="1" eType="ecore:EClass ../../org.asup.fw.java/model/fw-java.ecore#//JavaList"/>
      <eParameters name="element" lowerBound="1">
        <eGenericType eTypeParameter="#//ListUtil/addFirst/E"/>
      </eParameters>
    </eOperations>
    <eOperations name="addLast">
      <eTypeParameters name="E"/>
      <eParameters name="list" lowerBound="1" eType="ecore:EClass ../../org.asup.fw.java/model/fw-java.ecore#//JavaList"/>
      <eParameters name="element" lowerBound="1">
        <eGenericType eTypeParameter="#//ListUtil/addLast/E"/>
      </eParameters>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="URIUtil" abstract="true" interface="true"
      eSuperTypes="../../org.asup.fw.core/model/fw-core.ecore#//Service">
    <eOperations name="getBaseName" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eParameters name="uri" lowerBound="1" eType="ecore:EDataType ../../org.asup.fw.java/model/fw-java.ecore#//JavaURI"/>
    </eOperations>
  </eClassifiers>
</ecore:EPackage>
