/**
 *  Copyright (c) 2012, 2014 Sme.UP and others.
 *  All rights reserved. This program and the accompanying materials
 *  are made available under the terms of the Eclipse Public License v1.0
 *  which accompanies this distribution, and is available at
 *  http://www.eclipse.org/legal/epl-v10.html
 *
 * 
 * Contributors: 
 *   Mattia Rocchi - Initial API and implementation 
 */
package org.asup.db.core.base;

import java.io.InputStream;
import java.io.Reader;
import java.math.BigDecimal;
import java.net.URL;
import java.sql.Array;
import java.sql.Blob;
import java.sql.Clob;
import java.sql.Connection;
import java.sql.Date;
import java.sql.NClob;
import java.sql.ParameterMetaData;
import java.sql.PreparedStatement;
import java.sql.Ref;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.RowId;
import java.sql.SQLException;
import java.sql.SQLWarning;
import java.sql.SQLXML;
import java.sql.Time;
import java.sql.Timestamp;
import java.util.Calendar;

import org.asup.db.core.QPreparedStatement;

public class BasePreparedStatementImpl extends BaseNativeStatementImpl implements QPreparedStatement, PreparedStatement {

	private PreparedStatement rawPreparedStatement;
	
	public BasePreparedStatementImpl(PreparedStatement preparedStatement) {
		super(preparedStatement);
		this.rawPreparedStatement = preparedStatement;
	}

	public void addBatch() throws SQLException {
		rawPreparedStatement.addBatch();
	}

	public void addBatch(String sql) throws SQLException {
		rawPreparedStatement.addBatch(sql);
	}

	public void cancel() throws SQLException {
		rawPreparedStatement.cancel();
	}

	public void clearBatch() throws SQLException {
		rawPreparedStatement.clearBatch();
	}

	public void clearParameters() {
		try {
			rawPreparedStatement.clearParameters();
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	public void clearWarnings() throws SQLException {
		rawPreparedStatement.clearWarnings();
	}

	public void close() throws SQLException {
		rawPreparedStatement.close();
	}

	public void closeOnCompletion() throws SQLException {
		rawPreparedStatement.closeOnCompletion();
	}

	public boolean execute() throws SQLException {
		return rawPreparedStatement.execute();
	}

	public boolean execute(String sql, int autoGeneratedKeys) throws SQLException {
		return rawPreparedStatement.execute(sql, autoGeneratedKeys);
	}

	public boolean execute(String sql, int[] columnIndexes) throws SQLException {
		return rawPreparedStatement.execute(sql, columnIndexes);
	}

	public boolean execute(String sql, String[] columnNames) throws SQLException {
		return rawPreparedStatement.execute(sql, columnNames);
	}

	public boolean execute(String sql) throws SQLException {
		return rawPreparedStatement.execute(sql);
	}

	public int[] executeBatch() throws SQLException {
		return rawPreparedStatement.executeBatch();
	}

	public ResultSet executeQuery() throws SQLException {
		return rawPreparedStatement.executeQuery();
	}

	public ResultSet executeQuery(String sql) throws SQLException {
		return rawPreparedStatement.executeQuery(sql);
	}

	public int executeUpdate() throws SQLException {
		return rawPreparedStatement.executeUpdate();
	}

	public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
		return rawPreparedStatement.executeUpdate(sql, autoGeneratedKeys);
	}

	public int executeUpdate(String sql, int[] columnIndexes) throws SQLException {
		return rawPreparedStatement.executeUpdate(sql, columnIndexes);
	}

	public int executeUpdate(String sql, String[] columnNames) throws SQLException {
		return rawPreparedStatement.executeUpdate(sql, columnNames);
	}

	public int executeUpdate(String sql) throws SQLException {
		return rawPreparedStatement.executeUpdate(sql);
	}

	public Connection getConnection() throws SQLException {
		return rawPreparedStatement.getConnection();
	}

	public int getFetchDirection() throws SQLException {
		return rawPreparedStatement.getFetchDirection();
	}

	public int getFetchSize() throws SQLException {
		return rawPreparedStatement.getFetchSize();
	}

	public ResultSet getGeneratedKeys() throws SQLException {
		return rawPreparedStatement.getGeneratedKeys();
	}

	public int getMaxFieldSize() throws SQLException {
		return rawPreparedStatement.getMaxFieldSize();
	}

	public int getMaxRows() throws SQLException {
		return rawPreparedStatement.getMaxRows();
	}

	public ResultSetMetaData getMetaData() throws SQLException {
		return rawPreparedStatement.getMetaData();
	}

	public boolean getMoreResults() throws SQLException {
		return rawPreparedStatement.getMoreResults();
	}

	public boolean getMoreResults(int current) throws SQLException {
		return rawPreparedStatement.getMoreResults(current);
	}

	public ParameterMetaData getParameterMetaData() throws SQLException {
		return rawPreparedStatement.getParameterMetaData();
	}

	public int getQueryTimeout() throws SQLException {
		return rawPreparedStatement.getQueryTimeout();
	}

	public ResultSet getResultSet() throws SQLException {
		return rawPreparedStatement.getResultSet();
	}

	public int getResultSetConcurrency() throws SQLException {
		return rawPreparedStatement.getResultSetConcurrency();
	}

	public int getResultSetHoldability() throws SQLException {
		return rawPreparedStatement.getResultSetHoldability();
	}

	public int getResultSetType() throws SQLException {
		return rawPreparedStatement.getResultSetType();
	}

	public int getUpdateCount() throws SQLException {
		return rawPreparedStatement.getUpdateCount();
	}

	public SQLWarning getWarnings() throws SQLException {
		return rawPreparedStatement.getWarnings();
	}

	public boolean isCloseOnCompletion() throws SQLException {
		return rawPreparedStatement.isCloseOnCompletion();
	}

	public boolean isClosed() throws SQLException {
		return rawPreparedStatement.isClosed();
	}

	public boolean isPoolable() throws SQLException {
		return rawPreparedStatement.isPoolable();
	}

	public boolean isWrapperFor(Class<?> iface) throws SQLException {
		return rawPreparedStatement.isWrapperFor(iface);
	}

	public void setArray(int parameterIndex, Array x) throws SQLException {
		rawPreparedStatement.setArray(parameterIndex, x);
	}

	public void setAsciiStream(int parameterIndex, InputStream x, int length) throws SQLException {
		rawPreparedStatement.setAsciiStream(parameterIndex, x, length);
	}

	public void setAsciiStream(int parameterIndex, InputStream x, long length) throws SQLException {
		rawPreparedStatement.setAsciiStream(parameterIndex, x, length);
	}

	public void setAsciiStream(int parameterIndex, InputStream x) throws SQLException {
		rawPreparedStatement.setAsciiStream(parameterIndex, x);
	}

	public void setBigDecimal(int parameterIndex, BigDecimal x) throws SQLException {
		rawPreparedStatement.setBigDecimal(parameterIndex, x);
	}

	public void setBinaryStream(int parameterIndex, InputStream x, int length) throws SQLException {
		rawPreparedStatement.setBinaryStream(parameterIndex, x, length);
	}

	public void setBinaryStream(int parameterIndex, InputStream x, long length) throws SQLException {
		rawPreparedStatement.setBinaryStream(parameterIndex, x, length);
	}

	public void setBinaryStream(int parameterIndex, InputStream x) throws SQLException {
		rawPreparedStatement.setBinaryStream(parameterIndex, x);
	}

	public void setBlob(int parameterIndex, Blob x) throws SQLException {
		rawPreparedStatement.setBlob(parameterIndex, x);
	}

	public void setBlob(int parameterIndex, InputStream inputStream, long length) throws SQLException {
		rawPreparedStatement.setBlob(parameterIndex, inputStream, length);
	}

	public void setBlob(int parameterIndex, InputStream inputStream) throws SQLException {
		rawPreparedStatement.setBlob(parameterIndex, inputStream);
	}

	public void setBoolean(int parameterIndex, boolean x) throws SQLException {
		rawPreparedStatement.setBoolean(parameterIndex, x);
	}

	public void setByte(int parameterIndex, byte x) throws SQLException {
		rawPreparedStatement.setByte(parameterIndex, x);
	}

	public void setBytes(int parameterIndex, byte[] x) throws SQLException {
		rawPreparedStatement.setBytes(parameterIndex, x);
	}

	public void setCharacterStream(int parameterIndex, Reader reader, int length) throws SQLException {
		rawPreparedStatement.setCharacterStream(parameterIndex, reader, length);
	}

	public void setCharacterStream(int parameterIndex, Reader reader, long length) throws SQLException {
		rawPreparedStatement.setCharacterStream(parameterIndex, reader, length);
	}

	public void setCharacterStream(int parameterIndex, Reader reader) throws SQLException {
		rawPreparedStatement.setCharacterStream(parameterIndex, reader);
	}

	public void setClob(int parameterIndex, Clob x) throws SQLException {
		rawPreparedStatement.setClob(parameterIndex, x);
	}

	public void setClob(int parameterIndex, Reader reader, long length) throws SQLException {
		rawPreparedStatement.setClob(parameterIndex, reader, length);
	}

	public void setClob(int parameterIndex, Reader reader) throws SQLException {
		rawPreparedStatement.setClob(parameterIndex, reader);
	}

	public void setCursorName(String name) throws SQLException {
		rawPreparedStatement.setCursorName(name);
	}

	public void setDate(int parameterIndex, Date x, Calendar cal) throws SQLException {
		rawPreparedStatement.setDate(parameterIndex, x, cal);
	}

	public void setDate(int parameterIndex, Date x) throws SQLException {
		rawPreparedStatement.setDate(parameterIndex, x);
	}

	public void setDouble(int parameterIndex, double x) throws SQLException {
		rawPreparedStatement.setDouble(parameterIndex, x);
	}

	public void setEscapeProcessing(boolean enable) throws SQLException {
		rawPreparedStatement.setEscapeProcessing(enable);
	}

	public void setFetchDirection(int direction) throws SQLException {
		rawPreparedStatement.setFetchDirection(direction);
	}

	public void setFetchSize(int rows) throws SQLException {
		rawPreparedStatement.setFetchSize(rows);
	}

	public void setFloat(int parameterIndex, float x) throws SQLException {
		rawPreparedStatement.setFloat(parameterIndex, x);
	}

	public void setInt(int parameterIndex, int x) {
		try {
			rawPreparedStatement.setInt(parameterIndex, x);
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	public void setLong(int parameterIndex, long x) throws SQLException {
		rawPreparedStatement.setLong(parameterIndex, x);
	}

	public void setMaxFieldSize(int max) throws SQLException {
		rawPreparedStatement.setMaxFieldSize(max);
	}

	public void setMaxRows(int max) throws SQLException {
		rawPreparedStatement.setMaxRows(max);
	}

	public void setNCharacterStream(int parameterIndex, Reader value, long length) throws SQLException {
		rawPreparedStatement.setNCharacterStream(parameterIndex, value, length);
	}

	public void setNCharacterStream(int parameterIndex, Reader value) throws SQLException {
		rawPreparedStatement.setNCharacterStream(parameterIndex, value);
	}

	public void setNClob(int parameterIndex, NClob value) throws SQLException {
		rawPreparedStatement.setNClob(parameterIndex, value);
	}

	public void setNClob(int parameterIndex, Reader reader, long length) throws SQLException {
		rawPreparedStatement.setNClob(parameterIndex, reader, length);
	}

	public void setNClob(int parameterIndex, Reader reader) throws SQLException {
		rawPreparedStatement.setNClob(parameterIndex, reader);
	}

	public void setNString(int parameterIndex, String value) throws SQLException {
		rawPreparedStatement.setNString(parameterIndex, value);
	}

	public void setNull(int parameterIndex, int sqlType, String typeName) throws SQLException {
		rawPreparedStatement.setNull(parameterIndex, sqlType, typeName);
	}

	public void setNull(int parameterIndex, int sqlType) throws SQLException {
		rawPreparedStatement.setNull(parameterIndex, sqlType);
	}

	public void setObject(int parameterIndex, Object x, int targetSqlType, int scaleOrLength) throws SQLException {
		rawPreparedStatement.setObject(parameterIndex, x, targetSqlType, scaleOrLength);
	}

	public void setObject(int parameterIndex, Object x, int targetSqlType) throws SQLException {
		rawPreparedStatement.setObject(parameterIndex, x, targetSqlType);
	}

	public void setObject(int parameterIndex, Object x) throws SQLException {
		rawPreparedStatement.setObject(parameterIndex, x);
	}

	public void setPoolable(boolean poolable) throws SQLException {
		rawPreparedStatement.setPoolable(poolable);
	}

	public void setQueryTimeout(int seconds) throws SQLException {
		rawPreparedStatement.setQueryTimeout(seconds);
	}

	public void setRef(int parameterIndex, Ref x) throws SQLException {
		rawPreparedStatement.setRef(parameterIndex, x);
	}

	public void setRowId(int parameterIndex, RowId x) throws SQLException {
		rawPreparedStatement.setRowId(parameterIndex, x);
	}

	public void setSQLXML(int parameterIndex, SQLXML xmlObject) throws SQLException {
		rawPreparedStatement.setSQLXML(parameterIndex, xmlObject);
	}

	public void setShort(int parameterIndex, short x) throws SQLException {
		rawPreparedStatement.setShort(parameterIndex, x);
	}

	public void setString(int parameterIndex, String x) {
		try {
			rawPreparedStatement.setString(parameterIndex, x);
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	public void setTime(int parameterIndex, Time x, Calendar cal) throws SQLException {
		rawPreparedStatement.setTime(parameterIndex, x, cal);
	}

	public void setTime(int parameterIndex, Time x) throws SQLException {
		rawPreparedStatement.setTime(parameterIndex, x);
	}

	public void setTimestamp(int parameterIndex, Timestamp x, Calendar cal) throws SQLException {
		rawPreparedStatement.setTimestamp(parameterIndex, x, cal);
	}

	public void setTimestamp(int parameterIndex, Timestamp x) throws SQLException {
		rawPreparedStatement.setTimestamp(parameterIndex, x);
	}

	public void setURL(int parameterIndex, URL x) throws SQLException {
		rawPreparedStatement.setURL(parameterIndex, x);
	}

	@SuppressWarnings("deprecation")
	public void setUnicodeStream(int parameterIndex, InputStream x, int length) throws SQLException {
		rawPreparedStatement.setUnicodeStream(parameterIndex, x, length);
	}

	public <T> T unwrap(Class<T> iface) throws SQLException {
		return rawPreparedStatement.unwrap(iface);
	}
	
}
