<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="core" nsURI="http://www.asup.org/db/core" nsPrefix="db-core">
  <eClassifiers xsi:type="ecore:EClass" name="Column" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataType" lowerBound="1"
        eType="#//DataType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nullable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="precision" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scale" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Connection">
    <eOperations name="close" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="createStatement" lowerBound="1" eType="#//JDBCStatement" eExceptions="#//JDBCException"/>
    <eOperations name="createStatement" lowerBound="1" eType="#//JDBCStatement" eExceptions="#//JDBCException">
      <eParameters name="update" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eOperations>
    <eOperations name="getConnection" lowerBound="1" eType="#//JDBCConnection" eExceptions="#//JDBCException"/>
    <eOperations name="prepareStatement" lowerBound="1" eType="#//PreparedStatement"
        eExceptions="#//JDBCException">
      <eParameters name="sqlCommand" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connectionConfig" lowerBound="1"
        eType="#//ConnectionConfig"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="currentSchema" eType="#//Schema"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="database" lowerBound="1"
        eType="#//Database"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connectionFactory" lowerBound="1"
        eType="#//ConnectionFactory"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConnectionConfig" eSuperTypes="../../org.asup.fw.core/model/fw-core.ecore#//ServiceConfig">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="databaseName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="driver" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="password" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pluginName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="useCatalog" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="usePool" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="user" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConnectionFactory" abstract="true" eSuperTypes="../../org.asup.fw.core/model/fw-core.ecore#//Plugin ../../org.asup.fw.core/model/fw-core.ecore#//Service #//DataSourceFactory"/>
  <eClassifiers xsi:type="ecore:EClass" name="ConnectionFactoryRegistry" abstract="true">
    <eOperations name="lookup" lowerBound="1" eType="#//ConnectionFactory">
      <eParameters name="connectionConfig" lowerBound="1" eType="#//ConnectionConfig"/>
    </eOperations>
    <eGenericSuperTypes eClassifier="ecore:EClass ../../org.asup.fw.core/model/fw-core.ecore#//PluginRegistry">
      <eTypeArguments eClassifier="#//ConnectionFactory"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConnectionManager" abstract="true" eSuperTypes="../../org.asup.fw.core/model/fw-core.ecore#//Service">
    <eOperations name="createConnectionConfig" eType="#//ConnectionConfig">
      <eParameters name="dictionary" lowerBound="1">
        <eGenericType eClassifier="ecore:EDataType ../../org.asup.fw.java/model/fw-java.ecore#//JavaDictionary">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="getDatabaseConnection" eType="#//Connection">
      <eParameters name="config" lowerBound="1" eType="#//ConnectionConfig"/>
    </eOperations>
    <eOperations name="getDatabaseConnection" eType="#//Connection">
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="registerConnectionConfig" lowerBound="1">
      <eParameters name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="config" lowerBound="1" eType="#//ConnectionConfig"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Database">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="schemas" upperBound="-1"
        eType="#//Schema" eOpposite="#//Schema/database">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Si intendono gli schemi richiesti   dalle connection.&#xA;Se invece si desidera ottenere uno schema disponibile, ma non ancora caricato, utilizzare la funzione DatabaseConnection.getSchema(String name)."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DatabaseManager" abstract="true" eSuperTypes="../../org.asup.fw.core/model/fw-core.ecore#//Service">
    <eOperations name="createIndex" eExceptions="#//JDBCException">
      <eParameters name="connection" eType="#//Connection"/>
      <eParameters name="index" lowerBound="1" eType="#//Index"/>
    </eOperations>
    <eOperations name="createSchema" eExceptions="#//JDBCException">
      <eParameters name="connection" eType="#//Connection"/>
      <eParameters name="schema" eType="#//Schema"/>
      <eParameters name="deepCreation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eOperations>
    <eOperations name="createTable" eExceptions="#//JDBCException">
      <eParameters name="connection" eType="#//Connection"/>
      <eParameters name="table" lowerBound="1" eType="#//Table"/>
      <eParameters name="deepCreation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eOperations>
    <eOperations name="createView" eExceptions="#//JDBCException">
      <eParameters name="connection" eType="#//Connection"/>
      <eParameters name="view" eType="#//View"/>
    </eOperations>
    <eOperations name="deleteData" eExceptions="#//JDBCException">
      <eParameters name="connection" eType="#//Connection"/>
      <eParameters name="schema" lowerBound="1" eType="#//Schema"/>
    </eOperations>
    <eOperations name="deleteData" eExceptions="#//JDBCException">
      <eParameters name="connection" eType="#//Connection"/>
      <eParameters name="table" lowerBound="1" eType="#//Table"/>
    </eOperations>
    <eOperations name="dropIndex" eExceptions="#//JDBCException">
      <eParameters name="connection" eType="#//Connection"/>
      <eParameters name="index" lowerBound="1" eType="#//Index"/>
    </eOperations>
    <eOperations name="dropSchema" eExceptions="#//JDBCException">
      <eParameters name="connection" eType="#//Connection"/>
      <eParameters name="schema" lowerBound="1" eType="#//Schema"/>
    </eOperations>
    <eOperations name="dropTable" eExceptions="#//JDBCException">
      <eParameters name="connection" eType="#//Connection"/>
      <eParameters name="table" lowerBound="1" eType="#//Table"/>
    </eOperations>
    <eOperations name="dropView" eExceptions="#//JDBCException">
      <eParameters name="connection" eType="#//Connection"/>
      <eParameters name="view" lowerBound="1" eType="#//View"/>
    </eOperations>
    <eOperations name="getSchema" lowerBound="1" eType="#//Schema">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Ritorna uno schema del database se presente fra gli schemi memorizzati da precedenti richieste, altrimenti tramite accesso ai metadati; lo schema caricato verra' poi memorizzato nella cache per soddisfare nuove richieste."/>
      </eAnnotations>
      <eParameters name="connection" eType="#//Connection"/>
      <eParameters name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getTable" eType="#//Table">
      <eParameters name="connection" eType="#//Connection"/>
      <eParameters name="schema" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="table" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getIndex" eType="#//Index">
      <eParameters name="connection" eType="#//Connection"/>
      <eParameters name="schema" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="table" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="index" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DatabaseObject" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataSourceFactory" instanceClassName="org.osgi.service.jdbc.DataSourceFactory"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DataType">
    <eLiterals name="Identity" value="10" literal="IDENTITY"/>
    <eLiterals name="Character" value="20" literal="CHAR"/>
    <eLiterals name="Varchar" value="30" literal="VARCHAR"/>
    <eLiterals name="Decimal" value="40" literal="DECIMAL"/>
    <eLiterals name="Boolean" value="50" literal="BOOLEAN"/>
    <eLiterals name="Date" value="60" literal="DATE"/>
    <eLiterals name="Time" value="70" literal="TIME"/>
    <eLiterals name="TimeStamp" value="80" literal="TIMESTAMP"/>
    <eLiterals name="Integer" value="90" literal="INT"/>
    <eLiterals name="Float" value="100" literal="FLOAT"/>
    <eLiterals name="Graphical" value="110" literal="GRAPH"/>
    <eLiterals name="Text" value="120" literal="TEXT"/>
    <eLiterals name="Blob" value="130" literal="BLOB"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Index">
    <eOperations name="getFullName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="columns" upperBound="-1"
        eType="#//IndexColumn" containment="true" eOpposite="#//IndexColumn/index"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="object" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="schema" eType="#//Schema"
        eOpposite="#//Schema/indexes"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unique" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IndexColumn">
    <eStructuralFeatures xsi:type="ecore:EReference" name="index" lowerBound="1" eType="#//Index"
        eOpposite="#//Index/columns" eKeys="#//Index/name"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ordering" lowerBound="1"
        eType="#//OrderingType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sequence" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="JDBCConnection" instanceClassName="java.sql.Connection"
      serializable="false"/>
  <eClassifiers xsi:type="ecore:EDataType" name="JDBCException" instanceClassName="java.sql.SQLException"
      serializable="false"/>
  <eClassifiers xsi:type="ecore:EDataType" name="JDBCStatement" instanceClassName="java.sql.Statement"
      serializable="false"/>
  <eClassifiers xsi:type="ecore:EEnum" name="OrderingType">
    <eLiterals name="Ascend" value="10" literal="A"/>
    <eLiterals name="Descend" value="20" literal="D"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="PreparedStatement" instanceClassName="java.sql.PreparedStatement"
      serializable="false"/>
  <eClassifiers xsi:type="ecore:EClass" name="Schema">
    <eStructuralFeatures xsi:type="ecore:EReference" name="database" lowerBound="1"
        eType="#//Database" eOpposite="#//Database/schemas"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tables" upperBound="-1"
        eType="#//Table" containment="true" eOpposite="#//Table/schema"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="views" upperBound="-1"
        eType="#//View" containment="true" eOpposite="#//View/schema"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="indexes" upperBound="-1"
        eType="#//Index" containment="true" eOpposite="#//Index/schema"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="StatementType">
    <eLiterals name="Declare" value="10" literal="DECLARE"/>
    <eLiterals name="Prepare" value="20" literal="PREPARE"/>
    <eLiterals name="Open" value="30" literal="OPEN"/>
    <eLiterals name="Fetch" value="40" literal="FETCH"/>
    <eLiterals name="Insert" value="50" literal="INSERT"/>
    <eLiterals name="Update" value="60" literal="UPDATE"/>
    <eLiterals name="Delete" value="70" literal="DELETE"/>
    <eLiterals name="Close" value="80" literal="CLOSE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Table" eSuperTypes="#//DatabaseObject">
    <eOperations name="getFullName" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="columns" upperBound="-1"
        eType="#//TableColumn" containment="true" eOpposite="#//TableColumn/table"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="schema" eType="#//Schema"
        eOpposite="#//Schema/tables"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableColumn" eSuperTypes="#//Column">
    <eStructuralFeatures xsi:type="ecore:EReference" name="table" lowerBound="1" eType="#//Table"
        eOpposite="#//Table/columns" eKeys="#//Table/name"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="View" eSuperTypes="#//DatabaseObject">
    <eOperations name="getFullName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="columns" upperBound="-1"
        eType="#//ViewColumn" containment="true" eOpposite="#//ViewColumn/view"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="creationPlugin" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="IBMI"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="creationCommand" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="schema" eType="#//Schema"
        eOpposite="#//Schema/views"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ViewColumn" eSuperTypes="#//Column">
    <eStructuralFeatures xsi:type="ecore:EReference" name="view" lowerBound="1" eType="#//View"
        eOpposite="#//View/columns" eKeys="#//View/name"/>
  </eClassifiers>
</ecore:EPackage>
