<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="core" nsURI="http://www.asup.org/db/core" nsPrefix="db-core">
  <eClassifiers xsi:type="ecore:EClass" name="CatalogContainer">
    <eOperations name="isActive" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connectionConfig" lowerBound="1"
        eType="#//ConnectionConfig" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="catalog" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.datatools.modelbase.sql/model/sqlmodel.ecore#//schema/Catalog"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Connection" abstract="true" interface="true"
      eSuperTypes="../../org.asup.fw.core/model/fw-core.ecore#//ContextID">
    <eOperations name="close" eExceptions="#//DatabaseException"/>
    <eOperations name="commit" eExceptions="#//DatabaseException"/>
    <eOperations name="createStatement" lowerBound="1" eType="#//Statement" eExceptions="#//DatabaseException"/>
    <eOperations name="createStatement" lowerBound="1" eType="#//Statement" eExceptions="#//DatabaseException">
      <eParameters name="native" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eOperations>
    <eOperations name="getConnectionConfig" lowerBound="1" eType="#//ConnectionConfig"/>
    <eOperations name="getConnectionContext" eType="#//ConnectionContext"/>
    <eOperations name="getCurrentCatalog" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eOperations name="getDatabaseDefinition" lowerBound="1" eType="#//DatabaseDefinition"/>
    <eOperations name="prepareStatement" lowerBound="1" eType="#//PreparedStatement"
        eExceptions="#//DatabaseException">
      <eParameters name="sql" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="prepareStatement" lowerBound="1" eType="#//PreparedStatement"
        eExceptions="#//DatabaseException">
      <eParameters name="sql" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="native" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eOperations>
    <eOperations name="rollback" eExceptions="#//DatabaseException"/>
    <eOperations name="setAutoCommit" eExceptions="#//DatabaseException">
      <eParameters name="autoCommit" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eOperations>
    <eOperations name="resetAutoCommit"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConnectionConfig" eSuperTypes="../../org.asup.fw.core/model/fw-core.ecore#//ServiceConfig">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="autoCommit" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="persistent" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="driverName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="password" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="user" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vendor" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConnectionContext" abstract="true" eSuperTypes="../../org.asup.fw.core/model/fw-core.ecore#//Context"/>
  <eClassifiers xsi:type="ecore:EClass" name="ConnectionFactory" abstract="true" eSuperTypes="../../org.asup.fw.core/model/fw-core.ecore#//Plugin ../../org.asup.fw.core/model/fw-core.ecore#//Service">
    <eOperations name="createDatabaseConnection" eType="#//Connection">
      <eParameters name="connectionConfig" lowerBound="1" eType="#//ConnectionConfig"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConnectionFactoryRegistry" abstract="true">
    <eOperations name="lookup" lowerBound="1" eType="#//ConnectionFactory">
      <eParameters name="connectionConfig" lowerBound="1" eType="#//ConnectionConfig"/>
    </eOperations>
    <eGenericSuperTypes eClassifier="ecore:EClass ../../org.asup.fw.core/model/fw-core.ecore#//PluginRegistry">
      <eTypeArguments eClassifier="#//ConnectionFactory"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConnectionManager" abstract="true" eSuperTypes="../../org.asup.fw.core/model/fw-core.ecore#//Service">
    <eOperations name="createDatabaseConnection" eType="#//Connection">
      <eParameters name="connectionConfig" lowerBound="1" eType="#//ConnectionConfig"/>
    </eOperations>
    <eOperations name="createDatabaseConnection" eType="#//Connection">
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="registerConnectionConfig" lowerBound="1">
      <eParameters name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="connectionConfig" lowerBound="1" eType="#//ConnectionConfig"/>
    </eOperations>
    <eOperations name="createPropertiesByConnectionConfig" lowerBound="1" eType="ecore:EDataType ../../org.asup.fw.java/model/fw-java.ecore#//JavaProperties">
      <eParameters name="connectionConfig" lowerBound="1" eType="#//ConnectionConfig"/>
    </eOperations>
    <eOperations name="createPropertiesByVendorVersion" lowerBound="1" eType="ecore:EDataType ../../org.asup.fw.java/model/fw-java.ecore#//JavaProperties">
      <eParameters name="vendor" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConnectionProfile">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DatabaseContainer" eSuperTypes="../../org.asup.fw.core/model/fw-core.ecore#//ServiceConfig">
    <eStructuralFeatures xsi:type="ecore:EReference" name="connectionProfile" lowerBound="1"
        eType="#//ConnectionProfile" containment="true" eKeys="#//ConnectionProfile/name"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="database" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.datatools.modelbase.sql/model/sqlmodel.ecore#//schema/Database"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultCatalog" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.datatools.modelbase.sql/model/sqlmodel.ecore#//schema/Catalog"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="catalogs" lowerBound="1"
        upperBound="-1" eType="#//CatalogContainer" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DatabaseDefinition" abstract="true"
      interface="true">
    <eOperations name="supportsRelativeRecordNumber" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DatabaseObjectDef" abstract="true"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DatabaseException" instanceClassName="java.sql.SQLException"
      serializable="false"/>
  <eClassifiers xsi:type="ecore:EClass" name="DatabaseManager" abstract="true" eSuperTypes="../../org.asup.fw.core/model/fw-core.ecore#//Service">
    <eOperations name="createIndex" eExceptions="#//DatabaseException">
      <eParameters name="connection" eType="#//Connection"/>
      <eParameters name="table" lowerBound="1" eType="ecore:EClass ../../org.eclipse.datatools.modelbase.sql/model/sqlmodel.ecore#//tables/Table"/>
      <eParameters name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="index" lowerBound="1" eType="#//IndexDef"/>
    </eOperations>
    <eOperations name="createSchema" eExceptions="#//DatabaseException">
      <eParameters name="connection" eType="#//Connection"/>
      <eParameters name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="schema" eType="#//SchemaDef"/>
    </eOperations>
    <eOperations name="createTable" eExceptions="#//DatabaseException">
      <eParameters name="connection" eType="#//Connection"/>
      <eParameters name="schema" lowerBound="1" eType="ecore:EClass ../../org.eclipse.datatools.modelbase.sql/model/sqlmodel.ecore#//schema/Schema"/>
      <eParameters name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="table" lowerBound="1" eType="#//TableDef"/>
    </eOperations>
    <eOperations name="createView" eExceptions="#//DatabaseException">
      <eParameters name="connection" eType="#//Connection"/>
      <eParameters name="schema" lowerBound="1" eType="ecore:EClass ../../org.eclipse.datatools.modelbase.sql/model/sqlmodel.ecore#//schema/Schema"/>
      <eParameters name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="view" eType="#//ViewDef"/>
    </eOperations>
    <eOperations name="deleteData" eExceptions="#//DatabaseException">
      <eParameters name="connection" eType="#//Connection"/>
      <eParameters name="schema" lowerBound="1" eType="ecore:EClass ../../org.eclipse.datatools.modelbase.sql/model/sqlmodel.ecore#//schema/Schema"/>
    </eOperations>
    <eOperations name="deleteData" eExceptions="#//DatabaseException">
      <eParameters name="connection" eType="#//Connection"/>
      <eParameters name="table" lowerBound="1" eType="ecore:EClass ../../org.eclipse.datatools.modelbase.sql/model/sqlmodel.ecore#//tables/Table"/>
    </eOperations>
    <eOperations name="dropIndex" eExceptions="#//DatabaseException">
      <eParameters name="connection" eType="#//Connection"/>
      <eParameters name="index" lowerBound="1" eType="ecore:EClass ../../org.eclipse.datatools.modelbase.sql/model/sqlmodel.ecore#//constraints/Index"/>
    </eOperations>
    <eOperations name="dropSchema" eExceptions="#//DatabaseException">
      <eParameters name="connection" eType="#//Connection"/>
      <eParameters name="schema" lowerBound="1" eType="ecore:EClass ../../org.eclipse.datatools.modelbase.sql/model/sqlmodel.ecore#//schema/Schema"/>
    </eOperations>
    <eOperations name="dropTable" eExceptions="#//DatabaseException">
      <eParameters name="connection" eType="#//Connection"/>
      <eParameters name="table" lowerBound="1" eType="ecore:EClass ../../org.eclipse.datatools.modelbase.sql/model/sqlmodel.ecore#//tables/Table"/>
    </eOperations>
    <eOperations name="dropView" eExceptions="#//DatabaseException">
      <eParameters name="connection" eType="#//Connection"/>
      <eParameters name="view" lowerBound="1" eType="ecore:EClass ../../org.eclipse.datatools.modelbase.sql/model/sqlmodel.ecore#//tables/ViewTable"/>
    </eOperations>
    <eOperations name="getDatabaseContainer" lowerBound="1" eType="#//DatabaseContainer"/>
    <eOperations name="getIndex" eType="ecore:EClass ../../org.eclipse.datatools.modelbase.sql/model/sqlmodel.ecore#//constraints/Index">
      <eParameters name="connection" eType="#//Connection"/>
      <eParameters name="schema" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="index" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getSchema" lowerBound="1" eType="ecore:EClass ../../org.eclipse.datatools.modelbase.sql/model/sqlmodel.ecore#//schema/Schema">
      <eParameters name="connection" eType="#//Connection"/>
      <eParameters name="schema" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getTable" eType="ecore:EClass ../../org.eclipse.datatools.modelbase.sql/model/sqlmodel.ecore#//tables/Table">
      <eParameters name="connection" eType="#//Connection"/>
      <eParameters name="schema" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="table" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getView" eType="ecore:EClass ../../org.eclipse.datatools.modelbase.sql/model/sqlmodel.ecore#//tables/ViewTable">
      <eParameters name="connection" eType="#//Connection"/>
      <eParameters name="schema" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="table" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="isStarted" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DatabaseResultSet" instanceClassName="java.sql.ResultSet"
      serializable="false"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DatabaseDataType">
    <eLiterals name="Identity" value="10" literal="IDENTITY"/>
    <eLiterals name="Character" value="20" literal="CHAR"/>
    <eLiterals name="Varchar" value="30" literal="VARCHAR"/>
    <eLiterals name="Decimal" value="40" literal="DECIMAL"/>
    <eLiterals name="Boolean" value="50" literal="BOOLEAN"/>
    <eLiterals name="Date" value="60" literal="DATE"/>
    <eLiterals name="Time" value="70" literal="TIME"/>
    <eLiterals name="TimeStamp" value="80" literal="TIMESTAMP"/>
    <eLiterals name="Integer" value="90" literal="INT"/>
    <eLiterals name="Float" value="100" literal="FLOAT"/>
    <eLiterals name="Graphical" value="110" literal="GRAPH"/>
    <eLiterals name="Text" value="120" literal="TEXT"/>
    <eLiterals name="Blob" value="130" literal="BLOB"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IndexDef" eSuperTypes="#//DatabaseObjectDef">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="clustered" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="columns" upperBound="-1"
        eType="#//IndexColumnDef" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unique" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IndexColumnDef" eSuperTypes="#//DatabaseObjectDef">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ordering" lowerBound="1"
        eType="#//OrderingType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sequence" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="OrderingType">
    <eLiterals name="Ascend" value="10" literal="A"/>
    <eLiterals name="Descend" value="20" literal="D"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PreparedStatement" abstract="true" interface="true">
    <eOperations name="clearParameters"/>
    <eOperations name="close" lowerBound="1" eExceptions="#//DatabaseException"/>
    <eOperations name="execute" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        eExceptions="#//DatabaseException"/>
    <eOperations name="executeQuery" lowerBound="1" eType="#//DatabaseResultSet" eExceptions="#//DatabaseException"/>
    <eOperations name="executeUpdate" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        eExceptions="#//DatabaseException"/>
    <eOperations name="setInt">
      <eParameters name="position" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eOperations name="setString">
      <eParameters name="position" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QualifiedName">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="qualifiers" lowerBound="1"
        upperBound="3" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SchemaDef" eSuperTypes="#//DatabaseObjectDef"/>
  <eClassifiers xsi:type="ecore:EClass" name="Statement" abstract="true" interface="true">
    <eOperations name="close" lowerBound="1" eExceptions="#//DatabaseException"/>
    <eOperations name="execute" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        eExceptions="#//DatabaseException">
      <eParameters name="sql" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="executeQuery" lowerBound="1" eType="#//DatabaseResultSet" eExceptions="#//DatabaseException">
      <eParameters name="sql" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="executeUpdate" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        eExceptions="#//DatabaseException">
      <eParameters name="sql" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableDef" eSuperTypes="#//DatabaseObjectDef">
    <eStructuralFeatures xsi:type="ecore:EReference" name="columns" upperBound="-1"
        eType="#//TableColumnDef" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableColumnDef" eSuperTypes="#//DatabaseObjectDef">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataType" lowerBound="1"
        eType="#//DatabaseDataType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="default" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="length" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nullable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scale" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ViewDef" eSuperTypes="#//TableDef">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="creationPlugin" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="IBMI"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="creationCommand" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
