@echo off

if ""=="%1"  (
    echo Usage: %0 dbName
    goto FINE
)

db2 -x  CREATE DATABASE %1 USING CODESET ISO-8859-1 TERRITORY IT PAGESIZE 32 K
db2 -x  CONNECT TO %1
db2 -x  GRANT DBADM, CREATETAB, BINDADD, CONNECT, CREATE_NOT_FENCED, IMPLICIT_SCHEMA, LOAD ON DATABASE TO USER ASUP
db2 -x  UPDATE DATABASE CONFIGURATION FOR %1 USING LOGFILSIZ 1000
db2 -x  UPDATE DATABASE CONFIGURATION FOR %1 USING LOGPRIMARY 10
db2 -x  UPDATE DATABASE CONFIGURATION FOR %1 USING LOGSECOND 3

echo Database %1 created

:FINE