<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="syntax" nsURI="http://www.asup.org/db/syntax" nsPrefix="db-syntax">
  <eClassifiers xsi:type="ecore:EClass" name="DefinitionParser" abstract="true" eSuperTypes="#//StatementParser">
    <eOperations name="parseDefinition" eType="#//DefinitionParseResult" eExceptions="ecore:EDataType ../../org.asup.db.core/model/db-core.ecore#//DatabaseException">
      <eParameters name="stream" lowerBound="1" eType="ecore:EDataType ../../org.asup.fw.java/model/fw-java.ecore#//JavaInputStream"/>
    </eOperations>
    <eOperations name="parseDefinition" eType="#//DefinitionParseResult" eExceptions="ecore:EDataType ../../org.asup.db.core/model/db-core.ecore#//DatabaseException">
      <eParameters name="sql" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DefinitionParserRegistry" abstract="true">
    <eOperations name="lookup" lowerBound="1" eType="#//DefinitionParser">
      <eParameters name="connectionConfig" lowerBound="1" eType="ecore:EClass ../../org.asup.db.core/model/db-core.ecore#//ConnectionConfig"/>
    </eOperations>
    <eGenericSuperTypes eClassifier="ecore:EClass ../../org.asup.fw.core/model/fw-core.ecore#//PluginRegistry">
      <eTypeArguments eClassifier="#//DefinitionParser"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DefinitionParseError"/>
  <eClassifiers xsi:type="ecore:EClass" name="DefinitionParseResult">
    <eStructuralFeatures xsi:type="ecore:EReference" name="definitionStatement" eType="#//DefinitionStatement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="errorList" upperBound="-1"
        eType="#//DefinitionParseError"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DefinitionWriter" abstract="true" eSuperTypes="#//StatementWriter">
    <eOperations name="createSchema" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eParameters name="name" lowerBound="1" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
      <eParameters name="schema" lowerBound="1" eType="ecore:EClass ../../org.asup.db.core/model/db-core.ecore#//SchemaDef"/>
    </eOperations>
    <eOperations name="createTable" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eParameters name="schema" lowerBound="1" eType="ecore:EClass ../../org.eclipse.datatools.modelbase.sql/model/sqlmodel.ecore#//schema/Schema"/>
      <eParameters name="name" lowerBound="1" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
      <eParameters name="table" lowerBound="1" eType="ecore:EClass ../../org.asup.db.core/model/db-core.ecore#//TableDef"/>
    </eOperations>
    <eOperations name="createView" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eParameters name="schema" lowerBound="1" eType="ecore:EClass ../../org.eclipse.datatools.modelbase.sql/model/sqlmodel.ecore#//schema/Schema"/>
      <eParameters name="name" lowerBound="1" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
      <eParameters name="view" lowerBound="1" eType="ecore:EClass ../../org.asup.db.core/model/db-core.ecore#//ViewDef"/>
    </eOperations>
    <eOperations name="createIndex" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eParameters name="table" lowerBound="1" eType="ecore:EClass ../../org.eclipse.datatools.modelbase.sql/model/sqlmodel.ecore#//tables/Table"/>
      <eParameters name="name" lowerBound="1" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
      <eParameters name="index" lowerBound="1" eType="ecore:EClass ../../org.asup.db.core/model/db-core.ecore#//IndexDef"/>
    </eOperations>
    <eOperations name="dropSchema" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eParameters name="schema" lowerBound="1" eType="ecore:EClass ../../org.eclipse.datatools.modelbase.sql/model/sqlmodel.ecore#//schema/Schema"/>
    </eOperations>
    <eOperations name="dropTable" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eParameters name="table" lowerBound="1" eType="ecore:EClass ../../org.eclipse.datatools.modelbase.sql/model/sqlmodel.ecore#//tables/Table"/>
    </eOperations>
    <eOperations name="dropView" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eParameters name="view" lowerBound="1" eType="ecore:EClass ../../org.eclipse.datatools.modelbase.sql/model/sqlmodel.ecore#//tables/ViewTable"/>
    </eOperations>
    <eOperations name="dropIndex" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eParameters name="index" lowerBound="1" eType="ecore:EClass ../../org.eclipse.datatools.modelbase.sql/model/sqlmodel.ecore#//constraints/Index"/>
    </eOperations>
    <eOperations name="deleteData" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eParameters name="table" lowerBound="1" eType="ecore:EClass ../../org.eclipse.datatools.modelbase.sql/model/sqlmodel.ecore#//tables/Table"/>
    </eOperations>
    <eOperations name="insertData" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eParameters name="table" lowerBound="1" eType="ecore:EClass ../../org.eclipse.datatools.modelbase.sql/model/sqlmodel.ecore#//tables/Table"/>
    </eOperations>
    <eOperations name="selectData" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eParameters name="table" lowerBound="1" eType="ecore:EClass ../../org.eclipse.datatools.modelbase.sql/model/sqlmodel.ecore#//tables/Table"/>
    </eOperations>
    <eOperations name="writeDefinition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eParameters name="statement" lowerBound="1" eType="#//DefinitionStatement"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DefinitionWriterRegistry" abstract="true">
    <eOperations name="lookup" lowerBound="1" eType="#//DefinitionWriter">
      <eParameters name="connectionConfig" lowerBound="1" eType="ecore:EClass ../../org.asup.db.core/model/db-core.ecore#//ConnectionConfig"/>
    </eOperations>
    <eGenericSuperTypes eClassifier="ecore:EClass ../../org.asup.fw.core/model/fw-core.ecore#//PluginRegistry">
      <eTypeArguments eClassifier="#//DefinitionWriter"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DefinitionStatement" abstract="true"
      interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="NameHelper" abstract="true" eSuperTypes="../../org.asup.fw.core/model/fw-core.ecore#//Plugin ../../org.asup.fw.core/model/fw-core.ecore#//Service #//SQLObjectNameHelper">
    <eOperations name="resolveContainers" lowerBound="1">
      <eParameters name="query" lowerBound="1" eType="ecore:EClass ../../org.eclipse.datatools.modelbase.sql.query/model/SQLQueryModel.ecore#//QueryStatement"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NameHelperRegistry" abstract="true">
    <eOperations name="lookup" lowerBound="1" eType="#//NameHelper">
      <eParameters name="connectionConfig" lowerBound="1" eType="ecore:EClass ../../org.asup.db.core/model/db-core.ecore#//ConnectionConfig"/>
    </eOperations>
    <eGenericSuperTypes eClassifier="ecore:EClass ../../org.asup.fw.core/model/fw-core.ecore#//PluginRegistry">
      <eTypeArguments eClassifier="#//NameHelper"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QueryWriter" abstract="true" eSuperTypes="#//StatementWriter">
    <eOperations name="writeQuery" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eParameters name="statement" lowerBound="1" eType="ecore:EClass ../../org.eclipse.datatools.modelbase.sql.query/model/SQLQueryModel.ecore#//QueryStatement"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QueryWriterRegistry" abstract="true">
    <eOperations name="lookup" lowerBound="1" eType="#//QueryWriter">
      <eParameters name="connectionConfig" lowerBound="1" eType="ecore:EClass ../../org.asup.db.core/model/db-core.ecore#//ConnectionConfig"/>
    </eOperations>
    <eGenericSuperTypes eClassifier="ecore:EClass ../../org.asup.fw.core/model/fw-core.ecore#//PluginRegistry">
      <eTypeArguments eClassifier="#//QueryWriter"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QueryParser" abstract="true" eSuperTypes="#//StatementParser">
    <eOperations name="parseQuery" eType="#//SQLQueryParseResult" eExceptions="ecore:EDataType ../../org.asup.db.core/model/db-core.ecore#//DatabaseException">
      <eParameters name="stream" lowerBound="1" eType="ecore:EDataType ../../org.asup.fw.java/model/fw-java.ecore#//JavaInputStream"/>
    </eOperations>
    <eOperations name="parseQuery" eType="#//SQLQueryParseResult" eExceptions="ecore:EDataType ../../org.asup.db.core/model/db-core.ecore#//DatabaseException">
      <eParameters name="sql" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QueryParserRegistry" abstract="true">
    <eOperations name="lookup" lowerBound="1" eType="#//QueryParser">
      <eParameters name="connectionConfig" lowerBound="1" eType="ecore:EClass ../../org.asup.db.core/model/db-core.ecore#//ConnectionConfig"/>
    </eOperations>
    <eGenericSuperTypes eClassifier="ecore:EClass ../../org.asup.fw.core/model/fw-core.ecore#//PluginRegistry">
      <eTypeArguments eClassifier="#//QueryParser"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SQLObjectNameHelper" instanceClassName="org.eclipse.datatools.modelbase.sql.schema.helper.ISQLObjectNameHelper"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EDataType" name="SQLQueryParseResult" instanceClassName="org.eclipse.datatools.sqltools.parsers.sql.query.SQLQueryParseResult"/>
  <eClassifiers xsi:type="ecore:EClass" name="StatementWriter" abstract="true" eSuperTypes="../../org.asup.fw.core/model/fw-core.ecore#//Plugin ../../org.asup.fw.core/model/fw-core.ecore#//Service">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nameHelper" eType="#//NameHelper"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StatementParser" abstract="true" eSuperTypes="../../org.asup.fw.core/model/fw-core.ecore#//Plugin ../../org.asup.fw.core/model/fw-core.ecore#//Service"/>
  <eSubpackages name="ddl" nsURI="http://www.asup.org/db/syntax/ddl" nsPrefix="db-syntax-ddl">
    <eClassifiers xsi:type="ecore:EClass" name="CommitStatement" eSuperTypes="#//DefinitionStatement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="hold" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ConnectStatement" eSuperTypes="#//DefinitionStatement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="pwd" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="reset" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="to" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="user" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CreateAliasStatement" eSuperTypes="#//DefinitionStatement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="aliasName" eType="ecore:EClass ../../org.asup.db.core/model/db-core.ecore#//QualifiedName"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="tableName" eType="ecore:EClass ../../org.asup.db.core/model/db-core.ecore#//QualifiedName"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CreateIndexStatement" eSuperTypes="#//DefinitionStatement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="indexName" eType="ecore:EClass ../../org.asup.db.core/model/db-core.ecore#//QualifiedName"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="onTable" eType="ecore:EClass ../../org.asup.db.core/model/db-core.ecore#//QualifiedName"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sortBy" eType="ecore:EClass ../../org.asup.db.core/model/db-core.ecore#//IndexDef"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="unique" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CreateTableStatement" eSuperTypes="#//DefinitionStatement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="tableName" eType="ecore:EClass ../../org.asup.db.core/model/db-core.ecore#//QualifiedName"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="fields" lowerBound="1"
          upperBound="-1" eType="ecore:EClass ../../org.asup.db.core/model/db-core.ecore#//TableFieldDef"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DisconnectStatement" eSuperTypes="#//DefinitionStatement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="target" upperBound="0"
          eType="#//ddl/TargetItem"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="DropRange">
      <eLiterals name="RESTRICT"/>
      <eLiterals name="CASCADE" value="1"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="DropTarget">
      <eLiterals name="ALIAS"/>
      <eLiterals name="INDEX" value="1"/>
      <eLiterals name="VIEW" value="2"/>
      <eLiterals name="TABLE" value="3"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="TargetItem">
      <eLiterals name="ALL"/>
      <eLiterals name="CURRENT" value="1"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DropStatement" eSuperTypes="#//DefinitionStatement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="range" upperBound="0"
          eType="#//ddl/DropRange" defaultValueLiteral=""/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="targetName" eType="ecore:EClass ../../org.asup.db.core/model/db-core.ecore#//QualifiedName"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="target" eType="#//ddl/DropTarget"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="dml" nsURI="http://www.asup.org/db/syntax/dml" nsPrefix="db-syntax-dml">
    <eClassifiers xsi:type="ecore:EClass" name="ExtendedQuerySelect" eSuperTypes="#//dml/ExtendedQueryExpressionBody ../../org.eclipse.datatools.modelbase.sql.query/model/SQLQueryModel.ecore#//QuerySelect"/>
    <eClassifiers xsi:type="ecore:EClass" name="ExtendedQueryExpressionBody" eSuperTypes="../../org.eclipse.datatools.modelbase.sql.query/model/SQLQueryModel.ecore#//QueryExpressionBody">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="optimizeRecordsNumber"
          eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
